metadata:
  type: Postgres
  connection_string: postgresql://root@localhost:26257/defaultdb?sslmode=disable
objects:
  type: S3
  secret_key: wayne
  access_key: meowmeow
  hostname: localhost:9000
  bucket_name: portfolio-experiment
