metadata:
  type: Postgres
  connection_string: postgresql://root@localhost:26258/defaultdb?sslmode=disable
objects:
  type: S3
  secret_key: portfolio-dev
  access_key: dev-password
  hostname: localhost:9000
  bucket_name: portfolio-dev
