networks:
  roachnet:
    driver: bridge
services:
  region1:
    image: cockroachdb/cockroach:v23.1.10
    networks:
      - roachnet
    command:
      - start
      - --insecure
      - --accept-sql-without-tls
      - --join=region1:26257,region2:26257,region3:26257
      - --listen-addr=region1:26257
      - --sql-addr=region1:26258
    ports:
      - 26258:26258
      - 18080:18080
    volumes:
      - region1:/cockroach/cockrach-data
  region2:
    image: cockroachdb/cockroach:v23.1.10
    networks:
      - roachnet
    command:
      - start
      - --insecure
      - --accept-sql-without-tls
      - --join=region1:26257,region2:26257,region3:26257
      - --listen-addr=region2:26257
      - --sql-addr=region2:26258
    volumes:
      - region1:/cockroach/cockrach-data
  region3:
    image: cockroachdb/cockroach:v23.1.10
    networks:
      - roachnet
    command:
      - start
      - --insecure
      - --accept-sql-without-tls
      - --join=region1:26257,region2:26257,region3:26257
      - --listen-addr=region3:26257
      - --sql-addr=region3:26258
    volumes:
      - region1:/cockroach/cockrach-data
volumes:
  region1:
  region2:
  region3:
