networks:
  minionet:
    driver: bridge
  roachnet:
    driver: bridge
services:
  minio1:
    image: quay.io/minio/minio
    networks:
      - minionet
    command:
      - server
      - /data2
    ports:
      - 9000:9000
      - 9090:9090
    volumes:
      - minio2:/data2
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=password
      - MINIO_CONSOLE_ADDRESS=127.0.0.1:9090
  roach1:
    image: cockroachdb/cockroach:v23.1.10
    networks:
      - roachnet
    command:
      - start
      - --insecure
      - --accept-sql-without-tls
      - --join=roach1:26257,roach2:26257,roach3:26257
      - --listen-addr=roach1:26257
      - --sql-addr=roach1:26258
    ports:
      - 26258:26258
      - 18080:18080
    volumes:
      - roach1:/cockroach/cockrach-data
  roach2:
    image: cockroachdb/cockroach:v23.1.10
    networks:
      - roachnet
    command:
      - start
      - --insecure
      - --accept-sql-without-tls
      - --join=roach1:26257,roach2:26257,roach3:26257
      - --listen-addr=roach2:26257
      - --sql-addr=roach2:26258
    volumes:
      - roach2:/cockroach/cockrach-data
  roach3:
    image: cockroachdb/cockroach:v23.1.10
    networks:
      - roachnet
    command:
      - start
      - --insecure
      - --accept-sql-without-tls
      - --join=roach1:26257,roach2:26257,roach3:26257
      - --listen-addr=roach3:26257
      - --sql-addr=roach3:26258
    volumes:
      - roach3:/cockroach/cockrach-data
volumes:
  roach1:
  roach2:
  roach3:
  minio2:
