build:
  cargo build

build-refactor:
  # requires cargo-limit to be installed
  reset
  (cargo lbuild --color=always 2>&1) | less -R

watchexec target:
  watchexec \
    -c \
    -e toml,rs \
    -w justfile \
    -w ../portfolio_core/src \
    -w ../portfolio_core/Cargo.toml \
    -w ../portfolio_http/src \
    -w ../portfolio_http/Cargo.toml \
    -w ../portfolio_backend_postgres/src \
    -w ../portfolio_backend_postgres/Cargo.toml \
    -w ../portfolio_objectstore/src \
    -w ../portfolio_objectstore/Cargo.toml \
    -w ../oci-distribution-test/src \
    -w ../oci-distribution-test/Cargo.toml \
    --restart \
    just {{target}}

we-build-refactor:
  just watchexec build-refactor

we-build:
  just watchexec build
